version: '3'
services:
#  frontend:
#    build: ./src/frontend
#    ports:
#      - '5003:80'
#    depends_on:
#      - graphql
  graphql:
    build:
      context: ./src/WWDM
      dockerfile: WWDM.GraphQL.Server/Dockerfile
    ports:
      - 5001:80 
    depends_on:
      - db    
  db:
    build: 
      context: ./data/
      dockerfile: db.Dockerfile
    ports:
      - '3306:3306'
    expose:
      - 3306
  #images:
  #  build:
  #    context: ./src/WWDM
  #    dockerfile: WWDM.Images/Dockerfile      
  #  ports:
  #    - 5002:80
  #  depends_on:
  #    - db
  #  volumes:
  #    - ./data/private/shots:/var/shots:ro