version: '3'
services:
  frontend:
    build: ./src/frontend
    ports:
      - '80:80'
    depends_on:
      - graphql
    expose:
      - 80
  graphql:
    build:
      context: ./src/WWDM
      dockerfile: WWDM.GraphQL.Server/Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - db
    expose:
      - 5000
  db:
    build: 
      context: ./data/
      dockerfile: db.Dockerfile
    ports:
      - '3306:3306'
    expose:
      - 3306